# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.employee import Employee
from openapi_server import util

from openapi_server.models.employee import Employee  # noqa: E501

class Employees(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, employees=None):  # noqa: E501
        """Employees - a model defined in OpenAPI

        :param employees: The employees of this Employees.  # noqa: E501
        :type employees: List[Employee]
        """
        self.openapi_types = {
            'employees': List[Employee]
        }

        self.attribute_map = {
            'employees': 'employees'
        }

        self._employees = employees

    @classmethod
    def from_dict(cls, dikt) -> 'Employees':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Employees of this Employees.  # noqa: E501
        :rtype: Employees
        """
        return util.deserialize_model(dikt, cls)

    @property
    def employees(self):
        """Gets the employees of this Employees.


        :return: The employees of this Employees.
        :rtype: List[Employee]
        """
        return self._employees

    @employees.setter
    def employees(self, employees):
        """Sets the employees of this Employees.


        :param employees: The employees of this Employees.
        :type employees: List[Employee]
        """

        self._employees = employees
