---
openapi: 3.0.0
info:
  contact:
    email: support@vwt.digital
    name: Digital Ambition Team
    url: https://vwt-digital.github.io/
  description: Endpoint to dynamic manipulate data
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl.txt
  title: Dynamic Data Manipulation API
  version: 1.0.0
servers:
  - url: /
paths:
  /employee/{unique_id}:
    get:
      description: Returns an employee
      operationId: generic_get_single
      parameters:
        - explode: false
          in: path
          name: unique_id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: Returns an employee
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: No authorization token provided
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: Provided token doesn't have the required scope
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: Resource Not Found
      x-openapi-router-controller: openapi_server.controllers.default_controller
    put:
      description: Updates an employee
      operationId: generic_put_single
      parameters:
        - explode: false
          in: path
          name: unique_id
          required: true
          schema:
            format: uuid
            type: string
          style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeToAdd'
        description: Employee to update
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: succesfull PUT
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: No authorization token provided
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: Provided token doesn't have the required scope
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: Resource Not Found
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /employees:
    get:
      description: Returns a list of employees
      operationId: generic_get_multiple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employees'
          description: Returns a list of employees
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: No authorization token provided
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: Provided token doesn't have the required scope
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      description: Creates a new employee
      operationId: generic_post_single
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeToAdd'
        description: Employee to add
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: succesfull post
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: No authorization token provided
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
          description: Provided token doesn't have the required scope
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  parameters:
    EmployeeId:
      explode: false
      in: path
      name: unique_id
      required: true
      schema:
        format: uuid
        type: string
      style: simple
  responses:
    "204":
      description: No Content
    "400":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
      description: Bad Request
    "401":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
      description: No authorization token provided
    "403":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
      description: Provided token doesn't have the required scope
    "404":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
      description: Resource Not Found
  schemas:
    Employees:
      description: Collection of Employees
      example:
        - id: a0e7fd7e-7134-46da-b6be-f152cff23da5
          firstname: Izzy
          lastname: Van isteren
        - id: a0e7fd7e-7134-46da-b6be-f152cff23da5
          firstname: Peter
          lastname: Celie
      properties:
        employees:
          items:
            $ref: '#/components/schemas/Employee'
          type: array
      type: object
    Employee:
      description: Information about an employee
      example:
        id: a0e7fd7e-7134-46da-b6be-f152cff23da5
        firstname: Izzy
        lastname: Van isteren
      properties:
        id:
          format: uuid
          type: string
        firstname:
          maxLength: 100
          type: string
        lastname:
          maxLength: 100
          type: string
    EmployeeToAdd:
      description: Information about a new employee
      example:
        firstname: Izzy
        lastname: Van isteren
      properties:
        firstname:
          maxLength: 100
          type: string
        lastname:
          maxLength: 100
          type: string
    Response:
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
      type: object
