---
steps:
  # To deploy to Cloud Run use step 1 and 2.1 with all sub-steps.
  # To deploy to App Engine use step 1 and 2.2
  # 1. Generate DDM API models from spec
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ddm-openapi-models'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace:/local'
      - 'openapitools/openapi-generator-cli'
      - 'generate'
      - '-i'
      - '/local/openapi_server/openapi/openapi.yaml'
      - '-g'
      - 'python-flask'
      - '-o'
      - '/local'
      - '--global-property=models'
    dir: 'dynamic-data-manipulation-api/api_server'

  # 2.1.1 Build DDM API container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-ddm-container-image'
    waitFor: ['build-ddm-openapi-models']
    args:
      - 'build'
      - '-t'
      - 'eu.gcr.io/${PROJECT_ID}/dynamic-data-manipulation-api'
      - '-f'
      - './Dockerfile'
      - '.'
    dir: 'dynamic-data-manipulation-api/api_server'

  # 2.1.2 Push DDM API container to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-ddm-container-image'
    waitFor: ['build-ddm-container-image']
    args:
      - 'push'
      - 'eu.gcr.io/$PROJECT_ID/dynamic-data-manipulation-api'

  # 2.1.3 Deploy DDM API container to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-ddm-container-image'
    waitFor: ['push-ddm-container-image']
    args:
      - 'run'
      - 'deploy'
      - 'dynamic-data-manipulation-api'
      - '--image=eu.gcr.io/$PROJECT_ID/dynamic-data-manipulation-api'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--platform=managed'
      - '--memory=256M'

  # 2.2 Deploy DDM API to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    waitFor: ['build-ddm-openapi-models']
    timeout: 1200s
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--project=${PROJECT_ID}'
    dir: 'dynamic-data-manipulation-api/api_server'
