OAUTH_EXPECTED_AUDIENCE = ""
OAUTH_EXPECTED_ISSUER = ""
OAUTH_JWKS_URL = ""

OAUTH_E2E_EXPECTED_AUDIENCE = ""
OAUTH_E2E_EXPECTED_ISSUER = ""
OAUTH_E2E_JWKS_URL = ""
OAUTH_E2E_APPID = ""
OAUTH_E2E_SCOPES = ["", ""]

BASE_URL = 'https://example.com/'
ORIGINS = []

DATABASE_TYPE = ""
AUDIT_LOGS_NAME = ""
KMS_KEY_INFO = {
    "keyring": "",
    "key": "",
    "location": ""
}
